# Generated by Django 2.1.1 on 2018-10-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MountBikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('fake_price', models.PositiveIntegerField()),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=models.PositiveIntegerField())),
                ('img_link', models.CharField(max_length=300)),
                ('bike_type', models.CharField(choices=[('mountbike', 'горные велосипеды'), ('roadbike', 'шоссейные велосипеды'), ('bmx', 'BMX'), ('city_bike', 'городские велосипеды'), ('child_bike', 'детские велосипеды'), ('wheels', 'колеса'), ('frame', 'рамы'), ('shifter', 'переключатели'), ('brake', 'тормоза'), ('shirts', 'футболки'), ('shorts', 'шорты'), ('gloves', 'перчатки'), ('glases', 'очки'), ('tool', 'инструменты'), ('pump', 'насосы'), ('backpack', 'рюкзаки'), ('lamp', 'фонари'), ('fruit', 'фрукты'), ('water', 'вода'), ('nutrition', 'питание')], max_length=40)),
                ('available_XS', models.PositiveSmallIntegerField(default=0)),
                ('available_S', models.PositiveSmallIntegerField(default=0)),
                ('available_M', models.PositiveSmallIntegerField(default=0)),
                ('available_L', models.PositiveSmallIntegerField(default=0)),
                ('available_XL', models.PositiveSmallIntegerField(default=0)),
                ('available_no_size', models.PositiveSmallIntegerField(default=0)),
                ('available_gramms', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MountBikesDescription',
            fields=[
                ('mountbikes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bikefirst', serialize=False, to='bike_app.MountBikes', to_field='name')),
                ('description', models.CharField(max_length=5000)),
                ('frame', models.CharField(max_length=400)),
                ('fork', models.CharField(max_length=400)),
                ('ammort', models.CharField(max_length=400)),
                ('crank', models.CharField(max_length=400)),
                ('pedal', models.CharField(max_length=400)),
                ('front_shifter', models.CharField(max_length=400)),
                ('rear_shifter', models.CharField(max_length=400)),
                ('lever', models.CharField(max_length=400)),
                ('cassete', models.CharField(max_length=400)),
                ('chain', models.CharField(max_length=400)),
                ('rims', models.CharField(max_length=400)),
                ('tyres', models.CharField(max_length=400)),
                ('front_hub', models.CharField(max_length=400)),
                ('rear_hub', models.CharField(max_length=400)),
                ('front_brake', models.CharField(max_length=400)),
                ('rear_brake', models.CharField(max_length=400)),
                ('handlebar', models.CharField(max_length=400)),
                ('stem', models.CharField(max_length=400)),
                ('grips', models.CharField(max_length=400)),
                ('headset', models.CharField(max_length=400)),
                ('saddle', models.CharField(max_length=400)),
                ('seatpost', models.CharField(max_length=400)),
                ('warranty', models.PositiveSmallIntegerField(default=5)),
                ('unisex', models.BooleanField(default=True)),
            ],
        ),
    ]
