# Generated by Django 2.1.1 on 2018-09-28 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MountBikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_link', models.CharField(max_length=150)),
                ('available', models.BooleanField(default=True)),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MountBikesDescription',
            fields=[
                ('mountbikes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bikefirst', serialize=False, to='bike_app.MountBikes', to_field='name')),
                ('description', models.CharField(max_length=3000)),
                ('sex', models.BooleanField(default=True)),
                ('frame', models.CharField(max_length=200)),
                ('fork', models.CharField(max_length=200)),
                ('crank', models.CharField(max_length=200)),
                ('wheels', models.CharField(max_length=200)),
                ('front_shifter', models.CharField(max_length=200)),
                ('rear_shifter', models.CharField(max_length=200)),
                ('front_brake', models.CharField(max_length=200)),
                ('rear_brake', models.CharField(max_length=200)),
                ('handlebar', models.CharField(max_length=200)),
                ('seat', models.CharField(max_length=200)),
                ('warranty', models.SmallIntegerField(default=5)),
            ],
        ),
    ]
