# Generated by Django 2.1.1 on 2018-09-21 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MountBikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_link', models.CharField(max_length=150)),
                ('model_link', models.CharField(max_length=150)),
                ('available', models.BooleanField(default=True)),
                ('size', models.CharField(choices=[('XS', 'Super small'), ('SM', 'Small'), ('MD', 'Medium'), ('LA', 'Large'), ('XL', 'Extra large')], max_length=2)),
            ],
        ),
    ]
