# Generated by Django 2.1.1 on 2018-09-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountbikes',
            name='size',
            field=models.CharField(choices=[('XS', 'Super small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra large')], max_length=2),
        ),
    ]
